# Generated by Django 4.2.3 on 2024-12-03 18:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_professor_funcionario_and_more'),
        ('frequencias', '0002_alter_frequenciamodel_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequenciamodel',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.funcionario'),
        ),
        migrations.AlterField(
            model_name='frequenciamodel',
            name='hora_inicio',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
