# Generated by Django 4.2.3 on 2024-11-30 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_professor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professor',
            new_name='Funcionario',
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionarios'},
        ),
    ]
